version: "3.5"
services:
  database:
    image: 'postgres'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bigbro@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin