
version: "3.5"
services:
  backend:
    image: backend-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
      image: 'postgres:13.1-alpine'
      container_name: db
      environment:
        - POSTGRES_USER=compose-postgres
        - POSTGRES_PASSWORD=compose-postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bigbro@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin