spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testovoe
    username: postgres
    password: zx147d
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000

